a = set('abracadabra')
b = set('alacazam')
print("a集合中的元素：",a)
print("b集合中的元素：",b)
print("a和b的差集:",a - b)     
print("a和b的并集:",a | b)    
print("a和b的交集:",a & b)     
print("a和b中不同时存在的元素:",a ^ b)
print("a和b的真子值:",a < b)
print("a和b的子值:",a <= b)
print("a和b的真超值:",a > b)
print("a和b的超值:",a >= b)
print("a和b的相等:",a == b)
print("a和b的不相等:",a != b)
print("a属于b:",a in b)
print("a不属于b:",a not in b)
